name: practice on AWS CRED
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest  
    steps:
      - name: git checkout
        uses: actions/checkout@v7
      - name: Setup AWS CRED
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
